#!/usr/bin/env bash
# Regenerate dist/nsa.css from tokens.css + components.css.
# Also propagates VERSION to the sidebar.js version label.
#
# Run before tagging a release. No dependencies beyond bash + sed.
set -euo pipefail

cd "$(dirname "$0")"

VERSION="$(cat VERSION)"

# 1. Build dist/nsa.css
#    - New banner with version
#    - Google Fonts @import (IBM Plex)
#    - tokens.css with Microgramma paths rewritten from `fonts/` to `../fonts/`
#      (jsDelivr resolves these within the same release tag)
#    - components.css unmodified
{
  cat <<EOF
/* =========================================================
   NSA Design System v${VERSION} — Single-file distribution
   North Shore Automation · 2026
   ---------------------------------------------------------
   Drop-in stylesheet. Includes:
     • IBM Plex Sans/Mono via Google Fonts (auto-loaded)
     • Microgramma D Bold Extended (font files in ../fonts/)
     • All NSA tokens (color, type, space, radius, elevation)
     • All NSA UI components
   Generated by build.sh — do not edit by hand.
   ========================================================= */

@import url("https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap");

EOF
  sed 's|url("fonts/|url("../fonts/|g' tokens.css
  echo
  cat components.css
} > dist/nsa.css

# 2. Sync sidebar.js version label
sed -i.bak "s|^const NSA_DS_VERSION = '.*';|const NSA_DS_VERSION = 'v${VERSION}';|" sidebar.js
rm -f sidebar.js.bak

echo "Built dist/nsa.css and synced sidebar.js to v${VERSION}"
