#!/usr/bin/env bash
# Regenerate dist/nsa.css from tokens.css + components.css.
#
# Version resolution (in order):
#   1. $NSA_VERSION env var (used by .github/workflows/release.yml)
#   2. Most recent v* git tag (local dev with a real tag)
#   3. "dev" (no tags yet, e.g. fresh clone)
#
# dist/nsa.css is gitignored — the release workflow builds it fresh in
# the runner for Pages + Release artifacts. Run this locally only when
# you want to preview the concatenated output.
set -euo pipefail

cd "$(dirname "$0")"

if [ -n "${NSA_VERSION:-}" ]; then
  VERSION="$NSA_VERSION"
elif tag="$(git describe --tags --abbrev=0 --match 'v*' 2>/dev/null)"; then
  VERSION="${tag#v}"
else
  VERSION="dev"
fi

mkdir -p dist

{
  cat <<EOF
/* =========================================================
   NSA Design System v${VERSION} — Single-file distribution
   North Shore Automation · 2026
   ---------------------------------------------------------
   Drop-in stylesheet. Includes:
     • IBM Plex Sans/Mono via Google Fonts (auto-loaded)
     • Microgramma D Bold Extended (font files in ../fonts/)
     • All NSA tokens (color, type, space, radius, elevation)
     • All NSA UI components
   Generated by build.sh — do not edit by hand.
   ========================================================= */

@import url("https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap");

EOF
  sed 's|url("fonts/|url("../fonts/|g' tokens.css
  echo
  cat components.css
} > dist/nsa.css

echo "Built dist/nsa.css at v${VERSION}"
